
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module top (

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// KEY //////////
	input 		     [0:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7

);

logic [31:0] gpio_in_wire;
logic [31:0] gpio_out_wire;
logic [31:0] writeback_wire;
logic [11:0] pc_fetch_wire;
logic stall_fetch_wire;

//////////// CPU //////////
cpu processor(
	.clk(CLOCK_50),
	.rst(KEY[0]),
	.gpio_in(gpio_in_wire),
	.gpio_out(gpio_out_wire),
	.writeback_instruction(writeback_wire),
	.pc_test(pc_fetch_wire),
	.stall_test(stall_fetch_wire)
);

//=======================================================
//  7-Segment Display Setup
//=======================================================
assign gpio_in_wire = {14'b0, SW[17:0]};

hexdriver hex0 (gpio_out_wire[31:28], HEX0);
hexdriver hex1 (gpio_out_wire[27:24], HEX1);
hexdriver hex2 (gpio_out_wire[23:20], HEX2);
hexdriver hex3 (gpio_out_wire[19:16], HEX3); // out of switches, rest are hardwired
hexdriver hex4 (gpio_out_wire[15:12], HEX4); //This gets the last two switches
hexdriver hex5 (gpio_out_wire[11:8], HEX5); //All below are not used and hardwired to zero
hexdriver hex6 (gpio_out_wire[7:4], HEX6);
hexdriver hex7 (gpio_out_wire[3:0], HEX7);

endmodule
